export default [
  {
    title: 'SBG Core Elections 2019-20',
    date: new Date(2019, 4, 6),
    active: true,
  },
  {
    title: 'Khelaiya Club bagged 1st runners up at Chaos IIM-A',
    date: new Date(2019, 1, 27),
    link: 'https://docs.google.com/document/d/1fK1-gBNm6lHwuL3On9IsZM5pRPO6ZdJm-EXBpnr0VWo/edit?usp=sharing',
    active: true,
  },
  {
    title: 'Republic Day Celebration',
    date: new Date(2019, 1, 26),
    link: 'https://docs.google.com/document/d/1teJV79wwB0Fw7G0E-mwnihk7cTQxtwAGAoQZ0pmNOw8/edit?usp=sharing',
    active: true,
  },
  {
    title: 'Final Year batch photoshoot',
    date: new Date(2018, 11, 22),
    link: 'https://docs.google.com/document/d/1ZaBfd6CQ5eE3x-gEXcNEf3J8XKGtDOt9HJPHoIzeVfU/edit',
    active: true,
  },
  {
    title: 'SBG By-elections for the post of treasurer and secretary',
    date: new Date(2018, 11, 15),
    link: 'https://docs.google.com/document/d/1F9Ir6bwAEgiwWmzB--opDZuLbo5_zIhRaeTh9Oc1HJE/edit?usp=sharing',
    active: true,
  },
  {
    title: 'SBG General Meeting',
    date: new Date(2018, 10, 19),
    link: 'https://drive.google.com/open?id=0BzhQRE0vs1ndYkl4dkQ5cldjb1U',
    active: true,
  },
  {
    title: 'Mega Cleanliness Drive as a part of swachha Bharat',
    date: new Date(2018, 10, 2),
    link: 'https://docs.google.com/document/d/1ZfPWLrXBrfrZFTu61AgJQAdNEGNDSOAQ0q7MYMtdnY8/edit',
    active: true,
  },
  {
    title: 'SBG Budget Session',
    date: new Date(2018, 9, 7),
    link: 'https://docs.google.com/document/d/1E8QEIatubCZsWoY8Ylg1TE3SvuzaG0Ckn53YE7e9BQc/edit',
    active: true,
  },
  {
    title: 'Intra DA-IICT MUN',
    date: new Date(2017, 8, 24),
    link: 'https://drive.google.com/file/d/0B7018vFkJgoXcTRobldXeEFrS0U/view?usp=sharing',
    active: true,
  },
  {
    title: 'Educational visit to ISRO Labs, Ahmedabad',
    date: new Date(2017, 8, 20),
    link: 'https://docs.google.com/document/d/1AsJUMJzjQkDUtkH6oZfjCL63UCY0ngvNBYwp7G5MkPw/edit',
    active: false,
  },
  {
    title: 'Abhijit Ghodgaonkar got second rank on "Multiple Blind Folded" category in the Cubing Competition "SCMU 2017" (WCA) held in Mumbai.',
    date: new Date(2017, 8, 6),
    link: ' https://www.youtube.com/watch?v=AHtNa2H2sWM',
    active: true,
  },
  {
    title: 'Mosaic of Dr. Sarvepalli Radhakrishnan by The Cubing Club during Teacher\'s Day 2017',
    date: new Date(2017, 8, 5),
    link: 'https://www.youtube.com/watch?v=YBe4Sh9g3jI',
    active: false,
  },
  {
    title: 'Three members of MSTC selected as Microsoft Student Partner (2017-18)',
    date: new Date(2017, 7, 18),
    link: '',
    active: false,
  },
  {
    title: 'Team FruitSalad in ACM-ICPC World Finals',
    date: new Date(2017, 4, 27),
    link: '',
    active: false,
  },
  {
    title: 'Yash Kumar (B.Tech 3rd Year) and Karan Thakkar (B.Tech 3rd Year) secured runners up position at TCS Codevita, 2016, held at TCS Siruseri campus, Chennai',
    date: new Date(2017, 3, 7),
    link: '',
    active: false,
  },
  {
    title: 'Visit to an Old Age Home',
    date: new Date(2017, 9, 31),
    link: '',
    active: false,
  },
];
