export default [
  {
    header: 'Academic Committee',
    style: 'success',
    role: 'The Academic Committee works as an interface between the student community and the administration of the institute (including Dean Academics, Registrar, Institute committees, and the Director) for the development of the academic environment, and enhancement of academic life in DA-IICT.Their primary function is to convey the views, concerns, and problems, related to academics, of the student community to the institute administration (specifically, the various academic related committees of the institute) so as to enhance the quality of academic life and programs, and foster a conducive academic environment in the institute. Also, to organize activities that will enhance the academic aspects of student life in any and every possible way.',
    contact: {
      c_name: 'Jinesh Shah',
      dc_name: 'Kelay Shah',
      c_num: '+91 8980779867',
      dc_num: '+91 8000971501',
      webmail_id: 'sbg_academics@daiict.ac.in',
    },
  },
  {
    header: 'Annual Festival Committee',
    style: 'info',
    role: 'The Annual Festival Committee of DA-IICT works to provide a platform for students around the country to compete and showcase their talent. We are the proud organizers of the annual techno-cultural festival of DA-IICT – Synapse.\nSynapse is a celebration – a celebration of culture, technology and life. It is about realizing the underlying inherent junction of the three in an electrifying atmosphere. One of the most prominent college fests of Gujarat, it is a spectacle of our talent, aspirations, creativity and vision. Through exciting workshops, impressive events, and mesmerizing pro-nights, Synapse is a medium through which the youth can express their views; be it through art, culture, technological skills, knowledge or entertainment. It is a time when the student community comes forward to show its intensity, passion and enthusiasm. \nWe, at Synapse, hope to create the best four days at DA-IICT in an effort to give back to the DA-IICT community, students and faculty alike, for all their love, hard work, and dedication.',
    contact: {
      c_name: 'Chirang Malviya',
      dc_name: 'Aashay Binaykia',
      c_num: '+91 8128697799',
      dc_num: '+91 8981641460',
      webmail_id: 'synapse@daiict.ac.in',
      website: 'http://synapse.daiict.ac.in',
      youtube: 'https://www.youtube.com/user/SynapseDAIICT',
      instagram: 'https://www.instagram.com/synapsedaiict/',
    },
    reports: [
      {
        event: 'Synapse 2017 Glimpses',
        link: 'https://drive.google.com/drive/folders/1kkku0RBDUzXTDhbJo2MDg_UVGy4MftNI',
        date: '23th to 26th February, 2017',
      },
      {
        event: 'Youth Run',
        link: 'https://docs.google.com/document/d/1g9h2EmOiLFFUjZrW5-HqrOIEk2Kk2bbUZTe6H-2qJME/edit?usp=sharing',
        date: '22nd January, 2017',
      },
    ],
  },
  {
    header: 'Cafeteria Management Committee',
    style: 'default',
    role: 'Cafeteria Management Committee (CMC) addresses the issues related to cafeteria of DA-IICT. It does regular inspection of all the counters in the cafeteria and ensure that proper hygienic standards are maintained. It works as an intermediate body between the students and the administration of DA-IICT. It resolves issues raised by the students regarding cafeteria. They convey problems related to hygiene and quality of food available at DA-IICT cafeteria. Along with SBG Core and administration department of DA-IICT, they play an active role in deciding the price of food items and make sure that neither students nor the vendors are at loss. They also ensure proper working of night cafeteria of HOR-Women.',
    contact: {
      c_name: 'Adit Shah',
      dc_name: 'Vikas Parmar',
      c_num: '+91 7383441771',
      dc_num: '+91 7405546301',
      webmail_id: 'cmc@daiict.ac.in',
    },
  },
  {
    header: 'Cultural Committee',
    style: 'danger',
    role: 'The Cultural Committee is responsible for keeping the student community of DA-IICT culturally alive, the college life happening and simultaneously preserving our culture amongst the students. It also promotes various cultural activities like music, drama and dance amongst the student community. The Cultural Committee organises various big events all year round the academic calendar, thus creating an aura of excitement and enjoyment along with providing a platform for students to showcase their talent in front of the college. Some of the main OAT events include the Dance Nite, the Drama Nite, etc. Apart from these, the Cultural Committee also takes upon its onus, the celebrations of various festivals throughout the year including Janmashtami, Eid and, one of the most popular one, Navratri. With this, it makes an attempt to promote the significance of these festivals as well as generate a homely feeling for the students. The Cultural Committee recognises itself as an important aspect of the soul of a student’s life and strives to make the college life a colourful and memorable one.',
    contact: {
      c_name: 'Aaditya Thakkar',
      dc_name: 'Sravani Kalangi',
      c_num: '+91 9537791815',
      dc_num: '+91 9909659174',
      webmail_id: 'cultural@daiict.ac.in',
      facebook: 'https://www.facebook.com/DaiictCulturalCommittee/',
    },
    reports: [
      {
        event: 'Waltz - Dance Nite',
        link: 'https://docs.google.com/document/d/1fK1-gBNm6lHwuL3On9IsZM5pRPO6ZdJm-EXBpnr0VWo/edit?usp=sharing',
        date: '13th November, 2017',
      },
      {
        event: 'Halloween',
        link: 'https://docs.google.com/document/d/1teJV79wwB0Fw7G0E-mwnihk7cTQxtwAGAoQZ0pmNOw8/edit?usp=sharing',
        date: '4th November, 2017',
      },
      {
        event: 'Diwali',
        link: 'https://docs.google.com/document/d/1tEYPfFfcsov8twInesH0kYvWiGZkgseW9XT61OtYgxw/edit?usp=sharing',
        date: '19th October, 2017',
      },
      {
        event: 'Dussehra and Raavan Dahan',
        link: 'https://docs.google.com/document/d/1MGzlmmOA159SilnX3kjgvnaxC9qFYwwkEpe35xUWebU/edit?usp=sharing',
        date: '30th September, 2017',
      },
      {
        event: 'Ramleela',
        link: 'https://docs.google.com/document/d/1iDgTEaaq2_JKS4AQwNCN0WpBextYTEXmFLhWExyGaE4/edit?usp=sharing',
        date: '28th September, 2017',
      },
      {
        event: 'Garba Night',
        link: 'https://docs.google.com/document/d/1NXKaRVK-Uw4XMRCzio8FKRnDlLGDPbweJuun_SslaI4/edit?usp=sharing',
        date: '25th September, 2017',
      },
      {
        event: 'Maniere - The Fashion Night',
        link: 'https://docs.google.com/document/d/12d02l5SAOCPo3dPDmWM3vrfXz0jFoxbAY5cEC-xh7vc/edit?usp=sharing',
        date: '18th September, 2017',
      },
      {
        event: 'Teachers\' Day',
        link: 'https://docs.google.com/document/d/1r_XMKGiwMFLBeHZeb-QaofDqxfVG0yV5yEbrPuSWaqs/edit?usp=sharing',
        date: '5th September, 2017',
      },
      {
        event: 'Eid',
        link: 'https://docs.google.com/document/d/1_Ple1syMA5XJTFuH8I9dNdbYBBZ0R3l13FWnctOY1AE/edit?usp=sharing',
        date: '2nd September, 2017',
      },
      {
        event: 'Ganesh Chaturthi',
        link: 'https://docs.google.com/document/d/1Yt4Tme9idNKBrHJiv2toF2wmonPfhaGALAgi5RRh1Ik/edit?usp=sharing',
        date: '25th - 27th August, 2017',
      },
      {
        event: 'Janmashtami',
        link: 'https://docs.google.com/document/d/1SS05LL2RACYiEelDMt_hGujmw8uH2g7ZIxJc0Cb7ec4/edit?usp=sharing',
        date: '15th August, 2017',
      },
      {
        event: 'Cultural Weekend',
        link: 'https://docs.google.com/document/d/1_OvTMlIp5UFBApLVxib8HHq3H3gC1xeklqk0-xGc1ss/edit?usp=sharing',
        date: '11th - 13th August, 2017',
      },
    ],
  },
  {
    header: 'Hostel Management Committee',
    style: 'warning',
    role: 'Hostel Management Committee works for peaceful, clean and student friendly environment in the hostel of DA-IICT. The purpose of the HMC is to develop a healthier environment in the hostel lives of all the students and induce the interaction between the students of the Hostel by various activity and events. The Committee should carry out all the jobs of hostel management when required, under the supervision of wardens and hostel supervisor, thus increasing the efficiency of the hostel management. It also works as intermediate body between students and Administration, so we provide you platform to raise your request, concern, problems and complain so we can solve it or put it up to the concerned authorities. The most important duty of the HMC members is to identify the problems faced by their respective floor residents, and present them for follow-up to the Committee.  We also ensure the efficient use of the hostel resources by all hostel residents. Apart from these, we carry out several survey to solve the problems related to electrician, carpenter and plumber. We also maintain the TV Room and issue chess and carom to kill the leisure time of the students. We, at HMC , hope to create environment with peace and cleanliness in Hostel. Thus enhancing the quality life of the residents of the hostel by support of student community and Administration.',
    contact: {
      c_name: 'Harmish Ganatra',
      dc_name: 'Agam Shah',
      c_num: '+91 9428890707',
      dc_num: '+91 8866225667',
      webmail_id: 'hmc@daiict.ac.in',
    },
    reports: [
      {
        event: 'Cleanliness Drive',
        link: 'https://docs.google.com/document/d/1E8QEIatubCZsWoY8Ylg1TE3SvuzaG0Ckn53YE7e9BQc/edit?usp=sharing',
        date: '27th September - October, 2017',
      },
      {
        event: 'Mosquito Net Installation Drive',
        link: 'https://docs.google.com/document/d/1mhQRg5Wu4JMncBC-ANsHtbfqwdydXavSvaUcp2ECBIQ/edit?usp=sharing',
        date: '20th September, 2017',
      },
      {
        event: 'Fumigation',
        link: 'https://docs.google.com/document/d/1BSJ8EB7-xT0HYCx9tczdN8IwfNqzJJ_s0otCc01R5CY/edit?usp=sharing',
        date: '9th September, 2017',
      },
      {
        event: 'Newspaper Facility',
        link: 'https://docs.google.com/document/d/128TIzpHKj6i7BXgXqVuHPhihhOJY46Sm09e7wdp0k20/edit?usp=sharing',
        date: 'Since Semester beginning',
      },
    ],
  },
  {
    header: 'ICT Committee',
    style: 'danger',
    role: 'The primary role of the ICT Committee is to represent student views and issues related to ICT resources to the concerned authorities (Help Desk, System Admin, Web Committee and ICT Convener) and vice versa. Also, to conduct and/or coordinate sessions over various tools and technologies (eg. Moo- dle) which are used in daily life by the DAIICT community. Further, they play an active role in all the technical assistance required for all the events on campus including sound setup and pack up, maintenance of the technical inventory.',
    contact: {
      c_name: 'Jay Bhuva',
      dc_name: 'Megh Shah',
      c_num: '+91 9033063062',
      dc_num: '+91 9409265756',
      webmail_id: 'ict_sbg@daiict.ac.in',
    },
  },
  {
    header: 'Sports Committee',
    style: 'info',
    role: 'The Sports Committee of DA-IICT aims to showcase athletic intelligence and foster a positive and friendly environment among student community. Also, we are proud organizers of the annual inter-college sports festival of DA-IICT, “CONCOURS”. Concours is a celebration of sportsmanship and teamwork. One of the most prominent college festivals of Gujarat, it is a spectacle of out sporting culture and talent. We also organize sporting events like Athletic Meet, IBT (Inter Batch Tournaments), DCL (Da-iict Cricket League) and Outstation Trip to nurture the sporting spirit of the students. These are the times, when student community comes forward to show its passion and enthusiasm for sports. We, at Sports Committee, hope to create positive environment towards sports at DA-IICT with the hard work and dedication of faculties and student community.',
    contact: {
      c_name: 'Samarth Parikh',
      dc_name: 'Piyush Ajmeria',
      c_num: '+91 9428109090',
      dc_num: '+91 8109715078',
      webmail_id: 'sports@daiict.ac.in',
      website: 'http://concours.daiict.ac.in',
    },
  },
  {
    header: 'Student Placement Cell',
    style: 'success',
    role: 'The Placement Cell at DA-IICT is a concept in its own form. It works professionally abiding the hierarchy of the placement officer followed by the placement secretary, the faculty members and finally the student representatives from each stream. The hierarchy aims at touching all the aspects required for the smooth functioning of placement body of the reputed ICT forerunner Institution DA-IICT. The Placement Cell in DA-IICT works professionally with the Industry to explore opportunities for DA-IICT graduates for placement. The Cell makes its best efforts to reach out to all sub-sectors of the industry in order to ensure that DA-IICT graduates spread across the industry. The role of the Student Placement Cell, DA-IICT is to act just as an interface between the student community and the recruiters in order to organize and smoothen on-campus placements. An important function of SPC is to formulate the placement policy along with Placement Cell. It also works to compile requisite data –Student-related and company-related information. The main burden on the Student Placement Cell, DA-IICT is to ensure the best placements for the student community in both ways, qualitatively and quantitatively.',
    contact: {
      c_name: 'Akshay Miterani',
      dc_name: 'Sai Teja',
      c_num: '+91 8849377746',
      dc_num: '+91 7600637566',
      webmail_id: 'spc@daiict.ac.in',
      website: 'http://placement.daiict.ac.in',
    },
  },
];
